const trackedItems = [
  'Sorrowblade',
  'Shatterglass',
  'Tornado Trigger',
  'Metal Jacket',
  'Clockwork',
  'Serpent Mask',
  'Tension Bow',
  'Bonesaw',
  'Shiversteel',
  'Frostburn',
  'Fountain of Renewal',
  'Crucible',
  'Journey Boots',
  "Tyrant's Monocle",
  'Aftershock',
  'Broken Myth',
  'War Treads',
  'Atlas Pauldron',
  'Aegis',
  'Breaking Point',
  'Alternating Current',
  'Eve of Harvest',
  'Contraption',
  'Halcyon Chargers',
  'Stormcrown',
  'Poisoned Shiv',
  'Nullwave Gauntlet',
  'Echo',
  'Slumbering Husk',
];
