export default [
    { name:"Sorrowblade"        , short: "SB", internalName: "", category: "Weapon" },
    { name:"Shatterglass"       , short: "SG", internalName: "", category: "Crystal" },
    { name:"Tornado Trigger"    , short: "TT", internalName: "", category: "Weapon" },
    { name:"Metal Jacket"       , short: "MJ", internalName: "", category: "Defense" },
    { name:"Clockwork"          , short: "CW", internalName: "", category: "Utility" },
    { name:"Serpent Mask"       , short: "SM", internalName: "", category: "Weapon" },
    { name:"Tension Bow"        , short: "TB", internalName: "", category: "Weapon" },
    { name:"Bonesaw"            , short: "BS", internalName: "", category: "Weapon" },
    { name:"Shiversteel"        , short: "SS", internalName: "", category: "Utility" },
    { name:"Frostburn"          , short: "FB", internalName: "", category: "Crystal" },
    { name:"Fountain of Renewal", short: "FR", internalName: "", category: "Defense" },
    { name:"Crucible"           , short: "CB", internalName: "", category: "Defense" },
    { name:"Journey Boots"      , short: "JB", internalName: "", category: "Utility" },
    { name:"Tyrant\'s Monocle"  , short: "TM", internalName: "", category: "Weapon" },
    { name:"Aftershock"         , short: "AS", internalName: "", category: "Crystal" },
    { name:"Broken Myth"        , short: "BM", internalName: "", category: "Crystal" },
    { name:"War Treads"         , short: "WT", internalName: "", category: "Weapon" },
    { name:"Atlas Pauldron"     , short: "AP", internalName: "", category: "Defense" },
    { name:"Aegis"              , short: "AE", internalName: "", category: "Defense" },
    { name:"Breaking Point"     , short: "BP", internalName: "", category: "Weapon" },
    { name:"Alternating Current", short: "AC", internalName: "", category: "Crystal" },
    { name:"Eve of Harvest"     , short: "EH", internalName: "", category: "Crystal" },
    { name:"Contraption"        , short: "CT", internalName: "", category: "Utility" },
    { name:"Halcyon Chargers"   , short: "HC", internalName: "", category: "Utility" },
    { name:"Stormcrown"         , short: "SC", internalName: "", category: "Utility" },
    { name:"Poisoned Shiv"      , short: "PS", internalName: "", category: "Weapon" },
    { name:"Nullwave Gauntlet"  , short: "NG", internalName: "", category: "Utility" },
    { name:"Echo"               , short: "EH", internalName: "", category: "Crystal" },
    { name:"Slumbering Husk"    , short: "SH", internalName: "", category: "Defense" },
    { name:"Dragon\'s Eye"      , short: "DE", internalName: "", category: "Crystal" },
    { name:"Spellsword"         , short: "SS", internalName: "", category: "Weapon" },
    { name:"Spellfire"          , short: "SF", internalName: "", category: "Crystal" },
];